export const LIST_PRODUCT ='LIST_PRODUCT';
export const ADD_TO_CART ='ADD_TO_CART';
export const MESSAGE = 'MESSAGE';
export const MSG_ADD_SUCCESS = 'MSG_ADD_SUCCESS';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const MSG_DELETE_SUCCESS = 'MSG_DELETE_SUCCESS';
export const UPDATE_CART_ITEM ='UPDATE_CART_ITEM';
export const MSG_UPDATE_SUCCESS = 'MSG_UPDATE_SUCCESS';